export const LOAD_GIFS_SUCCESS = 'LOAD_GIFS_SUCCESS';
export const LOAD_GIFS_ERROR = 'LOAD_GIFS_ERROR';

export const LOAD_FAVORITE_GIFS_SUCCESS = 'LOAD_FAVORITE_GIFS_SUCCESS';

export const ADD_FAVORITE_GIF = 'ADD_FAVORITE_GIF';
export const REMOVE_FAVORITE_GIF = 'REMOVE_FAVORITE_GIF';

export const SET_FAVORITE_GIF = "SET_FAVORITE_GIF";

